import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [{ type: "autogenerated", dirName: "intro" }],
  docsSidebar: [
    { type: "category", label: "1. 개요", items: [{ type: "autogenerated", dirName: "intro/overview" }] },
    { type: "category", label: "2. 기본 연동 방식", items: [{ type: "autogenerated", dirName: "intro/method" }] },
  ],
  apiSidebar: [{ type: "autogenerated", dirName: "api-docs/endpoints" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
